// ── Theme tokens ──────────────────────────────────────────────────────────── //
export const THEMES = {
  dark: {
    bg:          "#090909",
    surface:     "#111111",
    surfaceUp:   "#161616",
    card:        "#141414",
    cardHover:   "#1a1a1a",
    cardActive:  "#0f1929",
    border:      "#202020",
    borderHover: "#2a2a2a",
    borderActive:"#3b82f6",
    text:        "#f0f0f0",
    textSub:     "#c0c0c0",
    muted:       "#555",
    label:       "#888",
    dot:         "#3b82f6",
    accent:      "#3b82f6",
    accentFg:    "#ffffff",
    accentGlow:  "#3b82f633",
    online:      "#22c55e",
    offline:     "#ef4444",
    warn:        "#f59e0b",
    topoOpacity: 0.045,
  },
  light: {
    bg:          "#f4f4f5",
    surface:     "#ffffff",
    surfaceUp:   "#f9f9f9",
    card:        "#ffffff",
    cardHover:   "#f5f5f5",
    cardActive:  "#eff6ff",
    border:      "#e4e4e7",
    borderHover: "#d0d0d8",
    borderActive:"#3b82f6",
    text:        "#09090b",
    textSub:     "#3f3f46",
    muted:       "#a1a1aa",
    label:       "#71717a",
    dot:         "#3b82f6",
    accent:      "#3b82f6",
    accentFg:    "#ffffff",
    accentGlow:  "#3b82f622",
    online:      "#16a34a",
    offline:     "#dc2626",
    warn:        "#d97706",
    topoOpacity: 0.06,
  },
};

// ── Known process → display metadata ─────────────────────────────────────── //
export const BRANDS = {
  "chrome.exe":          { bg: "#1a73e8", fg: "#fff",    letter: "C"  },
  "msedge.exe":          { bg: "#0078d4", fg: "#fff",    letter: "E"  },
  "firefox.exe":         { bg: "#ff5722", fg: "#fff",    letter: "F"  },
  "code.exe":            { bg: "#007acc", fg: "#fff",    letter: "VS" },
  "spotify.exe":         { bg: "#1db954", fg: "#fff",    letter: "S"  },
  "discord.exe":         { bg: "#5865f2", fg: "#fff",    letter: "D"  },
  "slack.exe":           { bg: "#4a154b", fg: "#fff",    letter: "Sl" },
  "notion.exe":          { bg: "#1a1a1a", fg: "#fff",    letter: "N"  },
  "figma.exe":           { bg: "#9747ff", fg: "#fff",    letter: "Fi" },
  "windowsterminal.exe": { bg: "#0c0c0c", fg: "#0af",    letter: ">" },
  "powershell.exe":      { bg: "#012456", fg: "#7dc6ff", letter: "PS" },
  "cmd.exe":             { bg: "#1e1e1e", fg: "#c8c8c8", letter: ">"  },
  "vlc.exe":             { bg: "#ff8c00", fg: "#fff",    letter: "V"  },
  "steam.exe":           { bg: "#1b2838", fg: "#c7d5e0", letter: "St" },
  "whatsapp.exe":        { bg: "#25d366", fg: "#fff",    letter: "W"  },
  "zoom.exe":            { bg: "#2d8cff", fg: "#fff",    letter: "Z"  },
  "teams.exe":           { bg: "#6264a7", fg: "#fff",    letter: "T"  },
  "postman.exe":         { bg: "#ff6c37", fg: "#fff",    letter: "P"  },
  "obsidian.exe":        { bg: "#7c3aed", fg: "#fff",    letter: "O"  },
  "thunderbird.exe":     { bg: "#0060df", fg: "#fff",    letter: "Tb" },
  "telegram.exe":        { bg: "#2aabee", fg: "#fff",    letter: "Tg" },
  "pycharm64.exe":       { bg: "#21d789", fg: "#000",    letter: "PC" },
  "idea64.exe":          { bg: "#fe315d", fg: "#fff",    letter: "IJ" },
  "webstorm64.exe":      { bg: "#00cdd7", fg: "#000",    letter: "WS" },
  "devenv.exe":          { bg: "#7a00d9", fg: "#fff",    letter: "VS" },
  "notepad++.exe":       { bg: "#4caf50", fg: "#fff",    letter: "N+" },
  "mpc-hc64.exe":        { bg: "#c00000", fg: "#fff",    letter: "M"  },
};

// ── Demo data ─────────────────────────────────────────────────────────────── //
export const DEMO_APPS = [
  { hwnd: 1001, display_name: "Chrome",    process_name: "chrome.exe",          is_active: true,  window_count: 1 },
  { hwnd: 1002, display_name: "VS Code",   process_name: "code.exe",            is_active: false, window_count: 2 },
  { hwnd: 1003, display_name: "Spotify",   process_name: "spotify.exe",         is_active: false, window_count: 1 },
  { hwnd: 1004, display_name: "Discord",   process_name: "discord.exe",         is_active: false, window_count: 1 },
  { hwnd: 1005, display_name: "WhatsApp",  process_name: "whatsapp.exe",        is_active: false, window_count: 1 },
  { hwnd: 1006, display_name: "Notion",    process_name: "notion.exe",          is_active: false, window_count: 1 },
  { hwnd: 1007, display_name: "Terminal",  process_name: "windowsterminal.exe", is_active: false, window_count: 1 },
];

const mkTab = (id, title, domain, active = false) => ({
  id, window_id: 1, title, url: `https://${domain}`,
  fav_icon: `https://www.google.com/s2/favicons?domain=${domain}&sz=64`,
  is_active: active,
});
export const DEMO_TABS = [
  mkTab(1,  "YouTube",         "youtube.com",         true),
  mkTab(2,  "Inbox (Gmail)",   "mail.google.com",     false),
  mkTab(3,  "Project Planner", "notion.so",           true),
  mkTab(4,  "UI Design",       "figma.com",           false),
  mkTab(5,  "GitHub",          "github.com",          false),
  mkTab(6,  "Docs",            "docs.google.com",     false),
  mkTab(7,  "Twitter",         "twitter.com",         false),
  mkTab(8,  "Medium",          "medium.com",          false),
  mkTab(9,  "ChatGPT",         "chat.openai.com",     true),
  mkTab(10, "Stack Overflow",  "stackoverflow.com",   false),
  mkTab(11, "LinkedIn",        "linkedin.com",        false),
  mkTab(12, "Drive",           "drive.google.com",    false),
  mkTab(13, "Calendar",        "calendar.google.com", false),
  mkTab(14, "Trello",          "trello.com",          false),
];
