// ── Theme tokens ──────────────────────────────────────────────────────────── //
export const THEMES = {
  dark: {
    bg:          "#090909",
    surface:     "#111111",
    surfaceUp:   "#161616",
    card:        "#141414",
    cardHover:   "#1a1a1a",
    cardActive:  "#0f1929",
    border:      "#202020",
    borderHover: "#2a2a2a",
    borderActive:"#3b82f6",
    text:        "#f0f0f0",
    textSub:     "#c0c0c0",
    muted:       "#555",
    label:       "#888",
    dot:         "#3b82f6",
    accent:      "#3b82f6",
    accentFg:    "#ffffff",
    accentGlow:  "#3b82f633",
    online:      "#22c55e",
    offline:     "#ef4444",
    warn:        "#f59e0b",
    topoOpacity: 0.045,
  },
  light: {
    bg:          "#f4f4f5",
    surface:     "#ffffff",
    surfaceUp:   "#f9f9f9",
    card:        "#ffffff",
    cardHover:   "#f5f5f5",
    cardActive:  "#eff6ff",
    border:      "#e4e4e7",
    borderHover: "#d0d0d8",
    borderActive:"#3b82f6",
    text:        "#09090b",
    textSub:     "#3f3f46",
    muted:       "#a1a1aa",
    label:       "#71717a",
    dot:         "#3b82f6",
    accent:      "#3b82f6",
    accentFg:    "#ffffff",
    accentGlow:  "#3b82f622",
    online:      "#16a34a",
    offline:     "#dc2626",
    warn:        "#d97706",
    topoOpacity: 0.06,
  },
};

// ── Known process → display metadata ─────────────────────────────────────── //
// 150+ apps across browsers, dev tools, communication, creative, gaming,
// productivity, media, security, utilities, and more.
export const BRANDS = {

  // ── Browsers ────────────────────────────────────────────────────────────
  "chrome.exe":              { bg: "#1a73e8", fg: "#fff",    letter: "C"   },
  "msedge.exe":              { bg: "#0078d4", fg: "#fff",    letter: "E"   },
  "firefox.exe":             { bg: "#e66000", fg: "#fff",    letter: "FF"  },
  "opera.exe":               { bg: "#cc1b00", fg: "#fff",    letter: "O"   },
  "operagx.exe":             { bg: "#7400c8", fg: "#fff",    letter: "GX"  },
  "brave.exe":               { bg: "#fb542b", fg: "#fff",    letter: "Br"  },
  "vivaldi.exe":             { bg: "#ef3939", fg: "#fff",    letter: "Vi"  },
  "safari.exe":              { bg: "#006cff", fg: "#fff",    letter: "Sa"  },
  "tor browser.exe":         { bg: "#7d4698", fg: "#fff",    letter: "Tor" },
  "waterfox.exe":            { bg: "#00acdc", fg: "#fff",    letter: "Wf"  },
  "arc.exe":                 { bg: "#ff6b35", fg: "#fff",    letter: "Arc" },
  "zen.exe":                 { bg: "#2d2d2d", fg: "#fff",    letter: "Zen" },

  // ── Code editors & IDEs ─────────────────────────────────────────────────
  "code.exe":                { bg: "#007acc", fg: "#fff",    letter: "VS"  },
  "code - insiders.exe":     { bg: "#24a035", fg: "#fff",    letter: "VSI" },
  "devenv.exe":              { bg: "#7a00d9", fg: "#fff",    letter: "VS"  },
  "pycharm64.exe":           { bg: "#21d789", fg: "#000",    letter: "PC"  },
  "idea64.exe":              { bg: "#fe315d", fg: "#fff",    letter: "IJ"  },
  "webstorm64.exe":          { bg: "#00cdd7", fg: "#000",    letter: "WS"  },
  "clion64.exe":             { bg: "#21d789", fg: "#000",    letter: "CL"  },
  "datagrip64.exe":          { bg: "#9775f8", fg: "#fff",    letter: "DG"  },
  "goland64.exe":            { bg: "#00adf0", fg: "#fff",    letter: "Go"  },
  "rider64.exe":             { bg: "#fe315d", fg: "#fff",    letter: "Rd"  },
  "rubymine64.exe":          { bg: "#fe315d", fg: "#fff",    letter: "RM"  },
  "phpstorm64.exe":          { bg: "#b345f1", fg: "#fff",    letter: "PS"  },
  "androidstudio64.exe":     { bg: "#3ddc84", fg: "#000",    letter: "AS"  },
  "eclipse.exe":             { bg: "#2c2255", fg: "#fff",    letter: "Ec"  },
  "notepad++.exe":           { bg: "#4caf50", fg: "#fff",    letter: "N+"  },
  "notepad.exe":             { bg: "#1e6bb8", fg: "#fff",    letter: "Np"  },
  "sublime_text.exe":        { bg: "#ff6900", fg: "#fff",    letter: "ST"  },
  "atom.exe":                { bg: "#66595c", fg: "#fff",    letter: "At"  },
  "brackets.exe":            { bg: "#1a91e8", fg: "#fff",    letter: "Bk"  },
  "cursor.exe":              { bg: "#000000", fg: "#fff",    letter: "Cu"  },
  "windsurf.exe":            { bg: "#0f4c75", fg: "#fff",    letter: "Wi"  },
  "zed.exe":                 { bg: "#084994", fg: "#fff",    letter: "Zd"  },

  // ── Terminals & shells ──────────────────────────────────────────────────
  "windowsterminal.exe":     { bg: "#0c0c0c", fg: "#00d4aa", letter: ">_"  },
  "powershell.exe":          { bg: "#012456", fg: "#7dc6ff", letter: "PS"  },
  "cmd.exe":                 { bg: "#1e1e1e", fg: "#c8c8c8", letter: ">"   },
  "wsl.exe":                 { bg: "#ff6600", fg: "#fff",    letter: "WSL" },
  "ubuntu.exe":              { bg: "#e95420", fg: "#fff",    letter: "Ub"  },
  "alacritty.exe":           { bg: "#1a1a2e", fg: "#e94560", letter: "Al"  },
  "hyper.exe":               { bg: "#000000", fg: "#fff",    letter: "Hy"  },
  "kitty.exe":               { bg: "#1a1a1a", fg: "#54a0ff", letter: "Kt"  },
  "git-bash.exe":            { bg: "#f05033", fg: "#fff",    letter: "Git" },
  "conhost.exe":             { bg: "#1e1e1e", fg: "#aaa",    letter: "Con" },

  // ── Communication & messaging ───────────────────────────────────────────
  "discord.exe":             { bg: "#5865f2", fg: "#fff",    letter: "D"   },
  "slack.exe":               { bg: "#4a154b", fg: "#fff",    letter: "Sl"  },
  "teams.exe":               { bg: "#6264a7", fg: "#fff",    letter: "T"   },
  "whatsapp.exe":            { bg: "#25d366", fg: "#fff",    letter: "W"   },
  "telegram.exe":            { bg: "#2aabee", fg: "#fff",    letter: "Tg"  },
  "zoom.exe":                { bg: "#2d8cff", fg: "#fff",    letter: "Z"   },
  "skype.exe":               { bg: "#00aff0", fg: "#fff",    letter: "Sk"  },
  "signal.exe":              { bg: "#3a76f0", fg: "#fff",    letter: "Sg"  },
  "viber.exe":               { bg: "#7360f2", fg: "#fff",    letter: "Vb"  },
  "line.exe":                { bg: "#06c755", fg: "#fff",    letter: "Li"  },
  "wechat.exe":              { bg: "#07c160", fg: "#fff",    letter: "We"  },
  "element.exe":             { bg: "#0dbd8b", fg: "#fff",    letter: "El"  },
  "mattermost.exe":          { bg: "#0058cc", fg: "#fff",    letter: "Mm"  },
  "webex.exe":               { bg: "#00bceb", fg: "#fff",    letter: "Wx"  },
  "thunderbird.exe":         { bg: "#0060df", fg: "#fff",    letter: "Tb"  },
  "outlook.exe":             { bg: "#0072c6", fg: "#fff",    letter: "Ol"  },

  // ── Music & audio ───────────────────────────────────────────────────────
  "spotify.exe":             { bg: "#1db954", fg: "#fff",    letter: "S"   },
  "tidal.exe":               { bg: "#000000", fg: "#fff",    letter: "Ti"  },
  "deezer.exe":              { bg: "#a238ff", fg: "#fff",    letter: "Dz"  },
  "applemusic.exe":          { bg: "#fa233b", fg: "#fff",    letter: "AM"  },
  "amazonmusic.exe":         { bg: "#00a8e0", fg: "#fff",    letter: "Az"  },
  "foobar2000.exe":          { bg: "#3a6ea5", fg: "#fff",    letter: "fb"  },
  "winamp.exe":              { bg: "#1a1a1a", fg: "#ffb300", letter: "WA"  },
  "musicbee.exe":            { bg: "#3d3d3d", fg: "#c06060", letter: "MB"  },
  "itunes.exe":              { bg: "#fc3c44", fg: "#fff",    letter: "iT"  },
  "audacity.exe":            { bg: "#0000cc", fg: "#fff",    letter: "Au"  },
  "vlc.exe":                 { bg: "#ff8c00", fg: "#fff",    letter: "VLC" },
  "fl studio.exe":           { bg: "#f5a623", fg: "#000",    letter: "FL"  },
  "ableton live.exe":        { bg: "#000000", fg: "#f5a623", letter: "Ab"  },

  // ── Video & streaming ───────────────────────────────────────────────────
  "mpc-hc64.exe":            { bg: "#c00000", fg: "#fff",    letter: "MPC" },
  "mpc-hc.exe":              { bg: "#c00000", fg: "#fff",    letter: "MPC" },
  "potplayer.exe":           { bg: "#1b1b1b", fg: "#e84393", letter: "PP"  },
  "potplayermini64.exe":     { bg: "#1b1b1b", fg: "#e84393", letter: "PP"  },
  "mpv.exe":                 { bg: "#333",    fg: "#fff",    letter: "mpv" },
  "kmplayer.exe":            { bg: "#1a1a2e", fg: "#e94560", letter: "KM"  },
  "obs64.exe":               { bg: "#302e31", fg: "#c27aff", letter: "OBS" },
  "obs.exe":                 { bg: "#302e31", fg: "#c27aff", letter: "OBS" },
  "streamlabs obs.exe":      { bg: "#31c3a2", fg: "#fff",    letter: "SL"  },
  "handbrake.exe":           { bg: "#e84848", fg: "#fff",    letter: "HB"  },
  "davinci resolve.exe":     { bg: "#1a1a1a", fg: "#e8c14a", letter: "DR"  },
  "premiere pro.exe":        { bg: "#2d0a47", fg: "#e8c14a", letter: "Pr"  },
  "after effects.exe":       { bg: "#1a0533", fg: "#9999ff", letter: "Ae"  },
  "vegas pro.exe":           { bg: "#1a1a1a", fg: "#e84393", letter: "VP"  },
  "kdenlive.exe":            { bg: "#1a3a5c", fg: "#fff",    letter: "Kd"  },
  "capcut.exe":              { bg: "#000000", fg: "#fff",    letter: "CC"  },

  // ── Design & creative ───────────────────────────────────────────────────
  "figma.exe":               { bg: "#9747ff", fg: "#fff",    letter: "Fi"  },
  "photoshop.exe":           { bg: "#001e36", fg: "#31a8ff", letter: "Ps"  },
  "illustrator.exe":         { bg: "#330000", fg: "#ff9a00", letter: "Ai"  },
  "xd.exe":                  { bg: "#2e001e", fg: "#ff61f6", letter: "XD"  },
  "indesign.exe":            { bg: "#49021f", fg: "#ff3366", letter: "Id"  },
  "lightroom.exe":           { bg: "#001a33", fg: "#31a8ff", letter: "Lr"  },
  "acrobat.exe":             { bg: "#b30000", fg: "#fff",    letter: "Ac"  },
  "inkscape.exe":            { bg: "#000000", fg: "#fff",    letter: "Ik"  },
  "gimp.exe":                { bg: "#4a4a4a", fg: "#fff",    letter: "Gp"  },
  "blender.exe":             { bg: "#ea7600", fg: "#fff",    letter: "Bl"  },
  "canva.exe":               { bg: "#00c4cc", fg: "#fff",    letter: "Cv"  },
  "sketchup.exe":            { bg: "#0058ad", fg: "#fff",    letter: "Su"  },
  "autocad.exe":             { bg: "#c00",    fg: "#fff",    letter: "CAD" },
  "clip studio paint.exe":   { bg: "#2a3f5f", fg: "#fff",    letter: "CSP" },
  "krita.exe":               { bg: "#3daee9", fg: "#fff",    letter: "Kr"  },
  "procreate.exe":           { bg: "#1e1e1e", fg: "#fff",    letter: "Pr"  },

  // ── Productivity & office ───────────────────────────────────────────────
  "notion.exe":              { bg: "#1a1a1a", fg: "#fff",    letter: "N"   },
  "obsidian.exe":            { bg: "#7c3aed", fg: "#fff",    letter: "Ob"  },
  "onenote.exe":             { bg: "#7719aa", fg: "#fff",    letter: "ON"  },
  "evernote.exe":            { bg: "#00a82d", fg: "#fff",    letter: "Ev"  },
  "winword.exe":             { bg: "#2b579a", fg: "#fff",    letter: "W"   },
  "excel.exe":               { bg: "#217346", fg: "#fff",    letter: "X"   },
  "powerpnt.exe":            { bg: "#b7472a", fg: "#fff",    letter: "P"   },
  "access.exe":              { bg: "#a4373a", fg: "#fff",    letter: "Ac"  },
  "publisher.exe":           { bg: "#077568", fg: "#fff",    letter: "Pu"  },
  "visio.exe":               { bg: "#3955a3", fg: "#fff",    letter: "Vi"  },
  "soffice.exe":             { bg: "#1c9d2c", fg: "#fff",    letter: "LO"  },
  "libreoffice.exe":         { bg: "#1c9d2c", fg: "#fff",    letter: "LO"  },
  "airtable.exe":            { bg: "#fcb400", fg: "#000",    letter: "AT"  },
  "clickup.exe":             { bg: "#7b68ee", fg: "#fff",    letter: "CU"  },
  "asana.exe":               { bg: "#f06a6a", fg: "#fff",    letter: "As"  },
  "trello.exe":              { bg: "#0052cc", fg: "#fff",    letter: "Tr"  },
  "monday.exe":              { bg: "#f6313a", fg: "#fff",    letter: "Mo"  },
  "jira.exe":                { bg: "#0052cc", fg: "#fff",    letter: "Ji"  },
  "confluence.exe":          { bg: "#0052cc", fg: "#fff",    letter: "Co"  },
  "linear.exe":              { bg: "#5e6ad2", fg: "#fff",    letter: "Ln"  },

  // ── Development tools ───────────────────────────────────────────────────
  "postman.exe":             { bg: "#ff6c37", fg: "#fff",    letter: "Pm"  },
  "insomnia.exe":            { bg: "#4000bf", fg: "#fff",    letter: "In"  },
  "github desktop.exe":      { bg: "#24292e", fg: "#fff",    letter: "GH"  },
  "sourcetree.exe":          { bg: "#0052cc", fg: "#fff",    letter: "ST"  },
  "gitkraken.exe":           { bg: "#179287", fg: "#fff",    letter: "GK"  },
  "fork.exe":                { bg: "#0058a3", fg: "#fff",    letter: "Fk"  },
  "tableplus.exe":           { bg: "#f6c344", fg: "#000",    letter: "TP"  },
  "dbeaver.exe":             { bg: "#3d6b9a", fg: "#fff",    letter: "DB"  },
  "sequel pro.exe":          { bg: "#9f5b17", fg: "#fff",    letter: "SP"  },
  "docker desktop.exe":      { bg: "#0db7ed", fg: "#fff",    letter: "Dk"  },
  "virtualbox.exe":          { bg: "#183a61", fg: "#fff",    letter: "VB"  },
  "vmware.exe":              { bg: "#607078", fg: "#fff",    letter: "VM"  },
  "wireshark.exe":           { bg: "#1679a7", fg: "#fff",    letter: "WS"  },
  "putty.exe":               { bg: "#1e1e1e", fg: "#75b5aa", letter: "Pu"  },
  "winscp.exe":              { bg: "#1f6fb2", fg: "#fff",    letter: "SC"  },
  "filezilla.exe":           { bg: "#b22222", fg: "#fff",    letter: "FZ"  },
  "mremoteng.exe":           { bg: "#0060ac", fg: "#fff",    letter: "mR"  },
  "royal ts.exe":            { bg: "#004b87", fg: "#fff",    letter: "RT"  },
  "charles.exe":             { bg: "#e8912d", fg: "#fff",    letter: "Ch"  },

  // ── Gaming ──────────────────────────────────────────────────────────────
  "steam.exe":               { bg: "#1b2838", fg: "#c7d5e0", letter: "St"  },
  "epicgameslauncher.exe":   { bg: "#2a2a2a", fg: "#fff",    letter: "EG"  },
  "gog galaxy.exe":          { bg: "#7c3aed", fg: "#fff",    letter: "GG"  },
  "origin.exe":              { bg: "#f56c2d", fg: "#fff",    letter: "Or"  },
  "easyfrontend.exe":        { bg: "#f56c2d", fg: "#fff",    letter: "EA"  },
  "battle.net.exe":          { bg: "#009ae4", fg: "#fff",    letter: "BN"  },
  "ubisoft connect.exe":     { bg: "#0070ff", fg: "#fff",    letter: "Ub"  },
  "robloxplayerbeta.exe":    { bg: "#e2231a", fg: "#fff",    letter: "Rb"  },
  "minecraft.exe":           { bg: "#5b8731", fg: "#fff",    letter: "Mc"  },
  "leagueclient.exe":        { bg: "#c69b3a", fg: "#000",    letter: "LoL" },
  "valorant.exe":            { bg: "#ff4655", fg: "#fff",    letter: "Val" },
  "csgo.exe":                { bg: "#de9b35", fg: "#fff",    letter: "CS"  },
  "cs2.exe":                 { bg: "#de9b35", fg: "#fff",    letter: "CS2" },
  "fortnite.exe":            { bg: "#00d4ff", fg: "#000",    letter: "FN"  },
  "overwatch.exe":           { bg: "#f99e1a", fg: "#fff",    letter: "OW"  },
  "genshinimpact.exe":       { bg: "#1a5276", fg: "#fff",    letter: "GI"  },
  "eldenring.exe":           { bg: "#c4a035", fg: "#000",    letter: "ER"  },
  "geforce now.exe":         { bg: "#76b900", fg: "#fff",    letter: "GFN" },
  "xboxapp.exe":             { bg: "#107c10", fg: "#fff",    letter: "XB"  },
  "playnite.exe":            { bg: "#ff6900", fg: "#fff",    letter: "PN"  },

  // ── Cloud storage & file sync ───────────────────────────────────────────
  "onedrive.exe":            { bg: "#0072c6", fg: "#fff",    letter: "OD"  },
  "dropbox.exe":             { bg: "#0061ff", fg: "#fff",    letter: "Db"  },
  "googledrivefs.exe":       { bg: "#1a73e8", fg: "#fff",    letter: "GD"  },
  "boxsync.exe":             { bg: "#0061d5", fg: "#fff",    letter: "Bx"  },
  "megasync.exe":            { bg: "#d9272e", fg: "#fff",    letter: "Mg"  },
  "nextcloud.exe":           { bg: "#0082c9", fg: "#fff",    letter: "NC"  },
  "syncthing.exe":           { bg: "#0891d1", fg: "#fff",    letter: "Sy"  },

  // ── Security & VPN ─────────────────────────────────────────────────────
  "nordvpn.exe":             { bg: "#4687ff", fg: "#fff",    letter: "NV"  },
  "expressvpn.exe":          { bg: "#da3940", fg: "#fff",    letter: "EV"  },
  "protonvpn.exe":           { bg: "#6d4aff", fg: "#fff",    letter: "PV"  },
  "mullvad vpn.exe":         { bg: "#44ad4d", fg: "#fff",    letter: "MV"  },
  "tailscale.exe":           { bg: "#0f2b46", fg: "#6db3f2", letter: "TS"  },
  "1password.exe":           { bg: "#1a8cff", fg: "#fff",    letter: "1P"  },
  "bitwarden.exe":           { bg: "#175ddc", fg: "#fff",    letter: "BW"  },
  "keepass.exe":             { bg: "#6cac35", fg: "#fff",    letter: "KP"  },
  "lastpass.exe":            { bg: "#cc2028", fg: "#fff",    letter: "LP"  },
  "malwarebytes.exe":        { bg: "#0157d6", fg: "#fff",    letter: "MB"  },

  // ── System & utilities ──────────────────────────────────────────────────
  "explorer.exe":            { bg: "#ffb900", fg: "#000",    letter: "Ex"  },
  "taskmgr.exe":             { bg: "#0078d4", fg: "#fff",    letter: "TM"  },
  "regedit.exe":             { bg: "#0078d4", fg: "#fff",    letter: "Re"  },
  "mmc.exe":                 { bg: "#0078d4", fg: "#fff",    letter: "MC"  },
  "7zfm.exe":                { bg: "#007bff", fg: "#fff",    letter: "7z"  },
  "winrar.exe":              { bg: "#8b0000", fg: "#fff",    letter: "WR"  },
  "bandizip.exe":            { bg: "#ff6600", fg: "#fff",    letter: "Bz"  },
  "cpu-z.exe":               { bg: "#185493", fg: "#fff",    letter: "CZ"  },
  "hwinfo64.exe":            { bg: "#1a1a1a", fg: "#e84393", letter: "HW"  },
  "msiafterburner.exe":      { bg: "#c00000", fg: "#fff",    letter: "AB"  },
  "speccy.exe":              { bg: "#1faaff", fg: "#fff",    letter: "Sp"  },
  "ccleaner.exe":            { bg: "#009000", fg: "#fff",    letter: "CC"  },
  "autoruns64.exe":          { bg: "#0078d4", fg: "#fff",    letter: "AR"  },
  "procexp64.exe":           { bg: "#0078d4", fg: "#fff",    letter: "PE"  },
  "everything.exe":          { bg: "#1464f4", fg: "#fff",    letter: "Ev"  },
  "keypirinha.exe":          { bg: "#2c2c2c", fg: "#fff",    letter: "KL"  },
  "powertoys.exe":           { bg: "#ffb900", fg: "#000",    letter: "PT"  },
  "flow launcher.exe":       { bg: "#5b5ea6", fg: "#fff",    letter: "FL"  },
  "ueli.exe":                { bg: "#6200ea", fg: "#fff",    letter: "Ue"  },
  "clipboard master.exe":    { bg: "#e84393", fg: "#fff",    letter: "CM"  },
  "autohotkey.exe":          { bg: "#334455", fg: "#fff",    letter: "AHK" },
  "rainmeter.exe":           { bg: "#232323", fg: "#9bbbce", letter: "Rm"  },
  "f.lux.exe":               { bg: "#f76707", fg: "#fff",    letter: "fx"  },
  "displayfusion.exe":       { bg: "#0078d4", fg: "#fff",    letter: "DF"  },
  "fancyzones.exe":          { bg: "#ffb900", fg: "#000",    letter: "FZ"  },

  // ── AI tools ────────────────────────────────────────────────────────────
  "claude.exe":              { bg: "#cc6b49", fg: "#fff",    letter: "Cl"  },
  "chatgpt.exe":             { bg: "#10a37f", fg: "#fff",    letter: "AI"  },
  "copilot.exe":             { bg: "#0078d4", fg: "#fff",    letter: "Co"  },
  "ollama.exe":              { bg: "#000000", fg: "#fff",    letter: "Ol"  },
  "lmstudio.exe":            { bg: "#6c3483", fg: "#fff",    letter: "LM"  },
  "jan.exe":                 { bg: "#0ea5e9", fg: "#fff",    letter: "Jn"  },

  // ── Note-taking & writing ───────────────────────────────────────────────
  "typora.exe":              { bg: "#3b3b3b", fg: "#fff",    letter: "Ty"  },
  "logseq.exe":              { bg: "#0f172a", fg: "#6ee7b7", letter: "Lg"  },
  "roamresearch.exe":        { bg: "#000",    fg: "#fff",    letter: "Ro"  },
  "bear.exe":                { bg: "#d4472f", fg: "#fff",    letter: "Be"  },
  "simplenote.exe":          { bg: "#3360cc", fg: "#fff",    letter: "SN"  },
  "zettlr.exe":              { bg: "#1cb27e", fg: "#fff",    letter: "Zt"  },
  "scrivener3.exe":          { bg: "#a5682a", fg: "#fff",    letter: "Sc"  },

  // ── Reading & documents ─────────────────────────────────────────────────
  "acrobat.exe":             { bg: "#b30000", fg: "#fff",    letter: "PDF" },
  "acrord32.exe":            { bg: "#b30000", fg: "#fff",    letter: "PDF" },
  "sumatrapdf.exe":          { bg: "#1c6da0", fg: "#fff",    letter: "Su"  },
  "okular.exe":              { bg: "#2196f3", fg: "#fff",    letter: "Ok"  },
  "calibre.exe":             { bg: "#4a4a4a", fg: "#fff",    letter: "Cb"  },
  "kindle.exe":              { bg: "#ff9900", fg: "#000",    letter: "Ki"  },

  // ── Social & news ───────────────────────────────────────────────────────
  "twitterapp.exe":          { bg: "#000000", fg: "#fff",    letter: "X"   },
  "instagram.exe":           { bg: "#c13584", fg: "#fff",    letter: "Ig"  },
  "facebook.exe":            { bg: "#1877f2", fg: "#fff",    letter: "Fb"  },
  "reddit.exe":              { bg: "#ff4500", fg: "#fff",    letter: "Rd"  },
  "linkedin.exe":            { bg: "#0a66c2", fg: "#fff",    letter: "In"  },
  "snapchat.exe":            { bg: "#fffc00", fg: "#000",    letter: "Sc"  },
  "tiktok.exe":              { bg: "#010101", fg: "#fff",    letter: "Tk"  },
  "pinterest.exe":           { bg: "#e60023", fg: "#fff",    letter: "Pi"  },
  "mastodon.exe":            { bg: "#563acc", fg: "#fff",    letter: "Ma"  },
  "bereal.exe":              { bg: "#000000", fg: "#fff",    letter: "BR"  },

  // ── Finance & crypto ────────────────────────────────────────────────────
  "coinbase.exe":            { bg: "#0052ff", fg: "#fff",    letter: "CB"  },
  "binance.exe":             { bg: "#f3ba2f", fg: "#000",    letter: "Bn"  },
  "robinhood.exe":           { bg: "#00c805", fg: "#fff",    letter: "Rh"  },
  "tradingview.exe":         { bg: "#131722", fg: "#2962ff", letter: "TV"  },
  "exodus.exe":              { bg: "#0b0c22", fg: "#8b61ff", letter: "Ex"  },
  "electrum.exe":            { bg: "#1a80c4", fg: "#fff",    letter: "El"  },
  "quickbooks.exe":          { bg: "#2ca01c", fg: "#fff",    letter: "QB"  },
  "quicken.exe":             { bg: "#cc0000", fg: "#fff",    letter: "Qk"  },
};

// ── Demo data ─────────────────────────────────────────────────────────────── //
export const DEMO_APPS = [
  { hwnd: 1001, display_name: "Chrome",    process_name: "chrome.exe",          is_active: true,  window_count: 1 },
  { hwnd: 1002, display_name: "VS Code",   process_name: "code.exe",            is_active: false, window_count: 2 },
  { hwnd: 1003, display_name: "Spotify",   process_name: "spotify.exe",         is_active: false, window_count: 1 },
  { hwnd: 1004, display_name: "Discord",   process_name: "discord.exe",         is_active: false, window_count: 1 },
  { hwnd: 1005, display_name: "WhatsApp",  process_name: "whatsapp.exe",        is_active: false, window_count: 1 },
  { hwnd: 1006, display_name: "Notion",    process_name: "notion.exe",          is_active: false, window_count: 1 },
  { hwnd: 1007, display_name: "Terminal",  process_name: "windowsterminal.exe", is_active: false, window_count: 1 },
];

const mkTab = (id, title, domain, active = false) => ({
  id, window_id: 1, title, url: `https://${domain}`,
  fav_icon: `https://www.google.com/s2/favicons?domain=${domain}&sz=64`,
  is_active: active,
});
export const DEMO_TABS = [
  mkTab(1,  "YouTube",         "youtube.com",         true),
  mkTab(2,  "Inbox (Gmail)",   "mail.google.com",     false),
  mkTab(3,  "Project Planner", "notion.so",           true),
  mkTab(4,  "UI Design",       "figma.com",           false),
  mkTab(5,  "GitHub",          "github.com",          false),
  mkTab(6,  "Docs",            "docs.google.com",     false),
  mkTab(7,  "Twitter",         "twitter.com",         false),
  mkTab(8,  "Medium",          "medium.com",          false),
  mkTab(9,  "ChatGPT",         "chat.openai.com",     true),
  mkTab(10, "Stack Overflow",  "stackoverflow.com",   false),
  mkTab(11, "LinkedIn",        "linkedin.com",        false),
  mkTab(12, "Drive",           "drive.google.com",    false),
  mkTab(13, "Calendar",        "calendar.google.com", false),
  mkTab(14, "Trello",          "trello.com",          false),
];